# Generated by Django 3.2.8 on 2021-10-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turial_title', models.CharField(max_length=200)),
                ('turial_content', models.TextField()),
                ('turial_publish', models.DateTimeField(verbose_name='date publisher')),
            ],
        ),
    ]
