# Generated by Django 3.2.9 on 2021-11-12 07:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20211111_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turial',
            name='turial_publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 14, 50, 48, 568947), verbose_name='date publisher'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('file_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('decription', models.TextField()),
                ('keyencrytion', models.CharField(choices=[('RSA', 'RSA'), ('ECC', 'ECC'), ('DSA', 'DSA')], max_length=255, null=True)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
