# Generated by Django 3.2.9 on 2021-11-12 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20211112_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turial',
            name='turial_publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 21, 0, 14, 664313), verbose_name='date publisher'),
        ),
    ]
